version: '3.9'

services:
  frontend:
    build:
      context: ./next-ai-flashcards
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./next-ai-flashcards:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./nest-ai-flashcards
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nest-ai-flashcards:/app
      - /app/node_modules
    env_file:
      - .env
